### PR TITLE
Clarify addition of blank lines in case and cond expressions

### PR DESCRIPTION
**Pull request by CraigCottingham**

### CODE REVIEW

**Comment by christopheradams** [comment]
The rule already shows a minimal example. Adding or removing the `do_something()` line does not change the formatting, so it's not needed.

However, I do agree the rule could be clarified. There are actually two rules at play here:

1) If any one `case` or `cond` clause (any "pattern match -> evaluate expression") is on multiple lines, then all clauses should be on multiple lines.
2) Multi-line `case` or `cond` clauses should be separated with a blank line.

An example showing both points:

  ```elixir
  # not preferred
  case arg do
    true ->  :ok
    false ->
      :error
  end

  # preferred
  case arg do
    true ->
      :ok

    false ->
      :error
  end
  ```

**Comment by christopheradams** [comment]
How about:

* If one clause in a `case` or `cond` expression span multiple lines, then all clauses should as well, separated by blank lines.

```elixir
# not preferred
case arg do
  true ->
    :ok
  false ->
    :error
end


# not preferred
case arg do
  true ->  :ok

  false ->
    :error
end

# preferred
case arg do
  true ->
    :ok

  false ->
    :error
end
```

**Comment by CraigCottingham** [comment]
The reason I added `do_something()` was to emphasize that each clause in the `case`/`cond` expression has more than one statement.

How about:

* If every clause in a `case` or `cond` expression has only a single statement, then each one should be on a single line, and there should be no blank lines between them.

```
case arg do
  true -> :ok
  false -> :error
end
```

* If at least one clause has more than one statement, then each clause should be wrapped at the arrow, and all clauses should be separated by blank lines.

```
case arg do
  true ->
    doSomething()
    :ok

  false ->
    :error
end
```

The wording feels kind of clunky, so I'm open to suggestions for improving it.

**Comment by christopheradams** [comment]
This section only covers rules that are enforced by the formatter, so it can’t recommend breaking the clauses across multiple lines (or not) for style reasons alone.

I believe my points 1 and 2 above are necessary and sufficient for the formatter rules.

**Comment by christopheradams** [comment]
I see your points above. I'm trying to think this through. The cases where the formatter will enforce multi-line case/cond expressions for all matches:

1. the evaluated expression itself has multiple clauses, like `true -> doSomething(); ok`
1. the evaluated expression is too long for a single line, like `true -> :really_long_expression`
1. the user formats it this way, `true ->\n  :ok`

I still maintain that all these reasons are handled by the rule as written, "If one clause in a `case` or cond expression span multiple lines"

**Comment by christopheradams** [comment]
How about this @CraigCottingham?

* If any `case` or `cond` clause needs to span more than one line, due to line length, multiple expressions in the clause body, or readability, use multi-line syntax for the whole statement.

   ```elixir
  # not preferred
  case arg do
    true -> IO.puts("ok"); :ok
    false -> :error
  end

  # not preferred
  case arg do
    true ->
      IO.puts("ok")
      :ok
    false -> :error
  end

  # preferred
  case arg do
    true ->
      IO.puts("ok")
      :ok

    false ->
      :error
  end
  ```

**Comment by CraigCottingham** [comment]
I like both this wording and the examples you've given.

Would you like me to modify my PR to match, or should it be closed and you'll make the change?

**Comment by christopheradams** [comment]
@CraigCottingham You're welcome to modify the PR and get the contributor credit.

I updated my suggestion above to mention separating the clauses with a blank line.

**Comment by christopheradams** [comment]
Thanks for the contribution @CraigCottingham. I merged the agreed changes and kept you as the commit author.

**Pull request merged**
