### PR TITLE
Update spanish translation

### PR DESCRIPTION
**Pull request by iver**
I updated the spanish version with the latest changes. Is it ok if I send my PR to this repository or should be requested to @albertoalmagro's repository?

### CODE REVIEW

**Comment by albertoalmagro** [comment]
@iver this one is the correct repository.

**Comment by iver** [comment]
@albertoalmagro sure! ... my first PR was with a change using i18n directory, but @christopheradams has a good point about the review, each language translation require more supervision by someone with respective language knowledge.

**Comment by christopheradams** [comment]
Thanks @iver for the Spanish language updates. And for understanding I'm not able to host all translations and keep up with their commits and issues.

**Comment by albertoalmagro** [comment]
If the desire was to have the translations reviewed then I believe the correct process would have been sending a pull request to my repo so that we could create a pull request and review it. Cheers!

**Comment by christopheradams** [comment]
@albertoalmagro I see I jumped to the conclusion that @iver was stepping up to maintain the Spanish translation and that I should point to his fork (which is what this PR does). That may have been wrong on my part. Do you intend to keep yours up to date? You should have preference here. :)

**Pull request merged**
