### PR TITLE
Add dogma code style linter

### PR DESCRIPTION
**Pull request by c-rack**

### CODE REVIEW

**Comment by niftyn8** [comment]
:wave: Sorry for the delay... I don't know much about the adoption of Dogma and how widespread it's use it but it looks like a great tool. Last I checked though Dogma used very different rules from this style guide. Is that still true? Not saying for sure that that's a blocker to merging this. Actually the only blockers to merging this I see right now are 1. There's a merge conflict now and 2. No one has given any feedback on this and I don't want to be the authority.

**Comment by DavidAntaramian** [comment]
@christopheradams We should probably take care of this since it's been open over a year. Nessa's comments still stand to reason in my mind, but I don't think it would be irresponsible to add Dogma as a reference tool considering it is configurable, extensible, and actively maintained, even if it doesn't enforce this style guide. Unless we're willing to write the tool scripts, no tool will maintain 100% compatibility with this style guide.

Sidebard: Regardless of the decision, if we maintain the tools section, we should probably also establish a set of parameters that determine whether a tool can be added to the list or not so that the decision isn't arbitrary.

**Comment by christopheradams** [comment]
Will do

**Comment by christopheradams** [comment]
As an alternative we could just link to Awesome Elixir's [Code Analysis](https://github.com/h4cc/awesome-elixir#code-analysis) section so that we don't duplicate effort or have to keep a tools list up to date.

**Comment by DavidAntaramian** [comment]
I think that's an acceptable approach

**Comment by christopheradams** [comment]
Ok, took care of it that way. Thanks!

**Pull request closed without merging**
